import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../repositories/app_repo.dart';
import '../services/export_service.dart';
import 'work_entry_screen.dart';
import 'master_screen.dart';
import 'reports_screen.dart';

class HomeScreen extends StatefulWidget { final VoidCallback onToggleTheme; const HomeScreen({super.key,required this.onToggleTheme}); @override State<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen>{ int index=0; final repo=AppRepo();
  Future<Map<String,double>> stats() async { final today=DateFormat('yyyy-MM-dd').format(DateTime.now()); final r=await repo.query('SELECT COALESCE(SUM(amount),0) income,COALESCE(SUM(total_hours),0) hours FROM work_entries'); final t=await repo.query('SELECT COALESCE(SUM(amount),0) income,COALESCE(SUM(total_hours),0) hours FROM work_entries WHERE date=?',[today]); final e=await repo.query('SELECT COALESCE(SUM(amount),0) x FROM expenses'); final o=await repo.query("SELECT COALESCE(SUM(amount),0) x FROM work_entries WHERE status!='Paid'"); return {'income':(r.first['income'] as num).toDouble(),'hours':(r.first['hours'] as num).toDouble(),'today':(t.first['income'] as num).toDouble(),'expenses':(e.first['x'] as num).toDouble(),'outstanding':(o.first['x'] as num).toDouble()}; }
  @override Widget build(BuildContext context){ final pages=[_Dashboard(repo:repo,refresh:()=>setState((){}),toggle:widget.onToggleTheme),const WorkEntryScreen(),MasterScreen(title:'Customers',table:'customers',fields:const ['name','mobile','address','village','notes']),const ReportsScreen(),MasterScreen(title:'More / Expenses',table:'expenses',fields:const ['date','category','amount','description','attachment'])]; return Scaffold(body:pages[index],bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(i)=>setState(()=>index=i),destinations:const [NavigationDestination(icon:Icon(Icons.dashboard_outlined),label:'Dashboard'),NavigationDestination(icon:Icon(Icons.work_outline),label:'Work'),NavigationDestination(icon:Icon(Icons.people_outline),label:'Customers'),NavigationDestination(icon:Icon(Icons.assessment_outlined),label:'Reports'),NavigationDestination(icon:Icon(Icons.more_horiz),label:'More')]),floatingActionButton:index==1?FloatingActionButton.extended(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const WorkEntryScreen(editId:null))).then((_){setState((){});}),icon:const Icon(Icons.add),label:const Text('New Work')):null); }
}
class _Dashboard extends StatelessWidget{final AppRepo repo;final VoidCallback refresh,toggle;const _Dashboard({required this.repo,required this.refresh,required this.toggle}); @override Widget build(BuildContext c)=>SafeArea(child:RefreshIndicator(onRefresh:()async=>refresh(),child:ListView(padding:const EdgeInsets.all(16),children:[Row(children:[const Expanded(child:Text('Work Time & Billing Manager',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold))),IconButton(onPressed:toggle,icon:const Icon(Icons.dark_mode_outlined))]),const SizedBox(height:12),FutureBuilder(future:Future.wait([repo.query('SELECT COUNT(*) c FROM work_entries'),repo.query('SELECT COUNT(*) c FROM customers'),repo.query('SELECT COUNT(*) c FROM categories')]),builder:(c,s){if(!s.hasData)return const LinearProgressIndicator();return Row(children:[_mini('Records',s.data![0].first['c']),_mini('Customers',s.data![1].first['c']),_mini('Categories',s.data![2].first['c'])]);}),const SizedBox(height:12),FutureBuilder(future:(_HomeStats(repo)),builder:(c,s){if(!s.hasData)return const CircularProgressIndicator();final x=s.data!;return GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,childAspectRatio:1.65,crossAxisSpacing:10,mainAxisSpacing:10,children:[_card('Today Earnings',x.today),_card('Today Hours',x.todayHours),_card('Total Earnings',x.income),_card('Total Expenses',x.expenses),_card('Net Profit',x.income-x.expenses),_card('Outstanding',x.outstanding)]);}),const SizedBox(height:16),const Text('Quick Actions',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),Wrap(spacing:8,children:[ActionChip(label:const Text('Work Categories'),avatar:const Icon(Icons.category),onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const MasterScreen(title:'Work Categories',table:'categories',fields:['name','description','rate_type','rate'])))),ActionChip(label:const Text('Employees'),avatar:const Icon(Icons.badge),onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const MasterScreen(title:'Employees',table:'employees',fields:['name','mobile','address'])))),ActionChip(label:const Text('Expenses'),avatar:const Icon(Icons.money_off),onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const MasterScreen(title:'Expenses',table:'expenses',fields:['date','category','amount','description','attachment'])))])]) ));}
Widget _mini(String s,Object? v)=>Expanded(child:Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[Text('$v',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Text(s)])))); Widget _card(String s,double v)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(s),const Spacer(),Text(s.contains('Hours')?'${v.toStringAsFixed(2)} h':'₹${v.toStringAsFixed(2)}',style:const TextStyle(fontSize:21,fontWeight:FontWeight.bold))])));
}
class _HomeStats{final double income,expenses,outstanding,today,todayHours;_HomeStats(this.income,this.expenses,this.outstanding,this.today,this.todayHours);}
Future<_HomeStats> _HomeStats(AppRepo r) async {final a=await r.query('SELECT COALESCE(SUM(amount),0)i,COALESCE(SUM(total_hours),0)h FROM work_entries');final b=await r.query('SELECT COALESCE(SUM(amount),0)e FROM expenses');final o=await r.query("SELECT COALESCE(SUM(amount),0)x FROM work_entries WHERE status!='Paid'");final t=DateFormat('yyyy-MM-dd').format(DateTime.now());final z=await r.query('SELECT COALESCE(SUM(amount),0)i,COALESCE(SUM(total_hours),0)h FROM work_entries WHERE date=?',[t]);return _HomeStats((a[0]['i']as num).toDouble(),(b[0]['e']as num).toDouble(),(o[0]['x']as num).toDouble(),(z[0]['i']as num).toDouble(),(z[0]['h']as num).toDouble());}
